/**:
  ros__parameters:

    filter1:
      name: front_filter
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -0.523599
        upper_angle: 0.523599
